/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COMMONAPI_DEMO_Demo_Service_STUB_HPP_
#define V1_COMMONAPI_DEMO_Demo_Service_STUB_HPP_

#include <functional>
#include <sstream>




#include <v1/commonapi/demo/DemoService.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>
#include <vector>

#include <mutex>

#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace demo {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service DemoService. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class DemoServiceStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual DemoService {
 public:
    ///Notifies all remote listeners about a change of value of the attribute carStatus.
    virtual void fireCarStatusAttributeChanged(const ::v1::commonapi::demo::DemoService::VehicleState &carStatus) = 0;


    virtual void deactivateManagedInstances() = 0;

    void lockCarStatusAttribute(bool _lockAccess) {
        if (_lockAccess) {
            carStatusMutex_.lock();
        } else {
            carStatusMutex_.unlock();
        }
    }

protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */
    std::recursive_mutex carStatusMutex_;

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for DemoService.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class DemoServiceStubRemoteEvent
{
public:
    virtual ~DemoServiceStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service DemoService to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class DemoServiceStub
    : public virtual CommonAPI::Stub<DemoServiceStubAdapter, DemoServiceStubRemoteEvent>
{
public:
    typedef std::function<void (uint32_t _result)> addReply_t;

    virtual ~DemoServiceStub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 2);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /// This is the method that will be called on remote calls on the method add.
    virtual void add(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _num1, uint32_t _num2, addReply_t _reply) = 0;
    /// Provides getter access to the attribute carStatus
    virtual const ::v1::commonapi::demo::DemoService::VehicleState &getCarStatusAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireCarStatusAttributeChanged(::v1::commonapi::demo::DemoService::VehicleState _value) {
    auto stubAdapter = CommonAPI::Stub<DemoServiceStubAdapter, DemoServiceStubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireCarStatusAttributeChanged(_value);
    }
    void lockCarStatusAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<DemoServiceStubAdapter, DemoServiceStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockCarStatusAttribute(_lockAccess);
    }


    using CommonAPI::Stub<DemoServiceStubAdapter, DemoServiceStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<DemoServiceStubAdapter, DemoServiceStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<DemoServiceStubAdapter, DemoServiceStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef DemoServiceStubRemoteEvent RemoteEventType;
    typedef DemoService StubInterface;
};

} // namespace demo
} // namespace commonapi
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COMMONAPI_DEMO_Demo_Service_STUB_HPP_
